--- Favor de llenar con los datos de los movimientos
--- que hagan en su base de datos.
--- Esto es para poder tener el mismo esqueme conforme se va desarrollando
--- Este archivo se deberia llenar bloque por bloque con la siguiente informacion:
--- Autor:
--- Fecha de push
--- EL bloque de codigo SQL que hace el cambio en la base de datos
--- Breve descripcion de que carajos hace...
--- Gracias